import Head from "next/head";

import Title from "@components/Title";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div className="text-3xl font-bold underline text-red-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title />
      </main>
    </div>
  );
};

export default Home;
